trigger:
- main

stages:
  - stage: 'Build'
    displayName: 'Build'
    jobs:
      - job: 'Package'
        displayName: 'Package the webpage'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Pipeline.Workspace)/www'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/MyWeb-$(Build.BuildId).zip'
              replaceExistingArchive: true
          - publish: '$(Build.ArtifactStagingDirectory)/MyWeb-$(Build.BuildId).zip'
            artifact: 'www'
